version: 2

models:
  - name: stg_payments
    description: "This model cleans and standardizes the raw payment data. It performs basic type casting and column renaming."
    columns:
      - name: payment_id
        description: "The unique identifier for the payment."
        tests:
          - unique
          - not_null
      - name: source_account_id
        description: "The account from which the payment was made."
      - name: destination_account_id
        description: "The account to which the payment was sent."
      - name: payment_reference
        description: "A reference string for the payment, provided by the payment system."
      - name: amount
        description: "The amount of the payment."
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              config: {severity: warn}
      - name: payment_timestamp
        description: "The timestamp when the payment event occurred."

  - name: stg_accounts
    description: "This model cleans and standardizes the raw account data."
    columns:
      - name: account_id
        description: "The unique identifier for the account."
        tests:
          - unique
          - not_null
      - name: opening_date
        description: "The date the account was opened."

  - name: stg_risk_feed
    description: "This model cleans and standardizes the raw risk feed data."
    columns:
      - name: account_id
        description: "The unique identifier for the account."
        tests:
          - not_null
      - name: risk_score
        description: "The risk score associated with the account at a point in time."

  - name: stg_fraud_cases
    description: "This model cleans and standardizes the raw fraud case data."
    columns:
      - name: payment_id
        description: "The unique identifier for the payment associated with the fraud case."
        tests:
          - unique
          - not_null
      - name: is_fraud_flag
        description: "A boolean flag indicating if the payment was determined to be fraudulent."