version: 2

models:
  - name: stg_payments
    description: "This model cleans and standardizes the raw payment data. It performs basic type casting and column renaming."
    columns:
      - name: payment_id
        description: "The unique identifier for the payment."
        tests:
          - unique
          - not_null
      - name: source_account_id
        description: "The account from which the payment was made."
      - name: payment_timestamp
        description: "The timestamp when the payment event occurred."

  - name: stg_accounts
    description: "This model cleans and standardizes the raw account data."
    columns:
      - name: account_id
        description: "The unique identifier for the account."
        tests:
          - unique
          - not_null
      - name: opening_date
        description: "The date the account was opened."

  - name: stg_risk_feed
    description: "This model cleans and standardizes the raw risk feed data."
    columns:
      - name: account_id
        description: "The unique identifier for the account."
        tests:
          - not_null
      - name: risk_score
        description: "The risk score associated with the account at a point in time."