apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-pod-template
  namespace: spark-jobs
data:
  driver-pod-template: |
    spec:
      initContainers:
      - name: copy-scripts
        image: busybox:1.36
        command: ["sh", "-c"]
        args:
        - |
          cp -r /scripts/* /opt/spark/work-dir/src/
          chmod +x /opt/spark/work-dir/src/*.py
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: work-dir
          mountPath: /opt/spark/work-dir
      containers:
      - name: spark-kubernetes-driver
        volumeMounts:
        - name: work-dir
          mountPath: /opt/spark/work-dir
      volumes:
      - name: scripts
        configMap:
          name: fraud-etl-scripts
      - name: work-dir
        emptyDir: {}
  executor-pod-template: |
    spec:
      initContainers:
      - name: copy-scripts
        image: busybox:1.36
        command: ["sh", "-c"]
        args:
        - |
          cp -r /scripts/* /opt/spark/work-dir/src/
          chmod +x /opt/spark/work-dir/src/*.py
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: work-dir
          mountPath: /opt/spark/work-dir
      containers:
      - name: spark-kubernetes-executor
        volumeMounts:
        - name: work-dir
          mountPath: /opt/spark/work-dir
      volumes:
      - name: scripts
        configMap:
          name: fraud-etl-scripts
      - name: work-dir
        emptyDir: {}
