version: 2

sources:
  - name: on_prem_raw_data
    description: "Raw data produced by Spark ETL"
    database: "{{ target.database }}"
    schema: public

    # Default freshness for all tables in this source
    freshness:
      warn_after: {count: 2, period: day}
      error_after: {count: 4, period: day}

    tables:
      - name: raw_payments
        description: "Raw payment events"
        # Override the default freshness for this specific table
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: "processing_ts"

      - name: raw_accounts
        description: "Account master data"
        loaded_at_field: "processing_ts" # Inherits the default freshness

      - name: raw_risk_feed
        description: "Risk scoring feed"
        loaded_at_field: "processing_ts" # Inherits the default freshness

      - name: raw_fraud_cases
        description: "Fraud case history"
        loaded_at_field: "processing_ts" # Inherits the default freshness
