apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: my-nodepool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: ephemeral # Use ephemeral storage for fast, local development
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 4.1.1
    # The number of replicas is now controlled by the KafkaNodePool
    listeners:
      # Internal listener for cluster-to-cluster communication (e.g., Spark jobs)
      - name: plain
        port: 9092
        type: internal
        tls: false
      # External listener for host machine access (e.g., data producer script)
      # The name 'external' is used so the service name matches what the producer script expects.
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      # Default retention policy for all topics to prevent filling up ephemeral storage.
      # Deletes messages when the log size for a partition reaches 1GB.
      log.retention.bytes: 1073741824
  entityOperator:
    topicOperator: {}
    userOperator: {}