# This is the main configuration file for your dbt project.
# For more information on configuring this file, see the dbt documentation:
# https://docs.getdbt.com/docs/configuring-projects

name: 'fraud_detection_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which dbt profile to use.
profile: 'fraud_detection_dbt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example, we're configuring all models in the `example`
# directory to be materialized as tables.
models:
  fraud_detection_dbt:
    # Config indicated by + and applies to all files under models/
    +materialized: table
    example:
      +materialized: view