fraud_detection_dbt:
  target: dev # This is the default target dbt will use when you run commands locally
  outputs:
    dev:
      type: postgres
      host: localhost # Or your local dev DB host
      user: local_user
      password: local_password
      port: 5432
      dbname: airflow
      schema: dev_{{ env_var('USER', 'default') }} # Creates a unique schema for each developer
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('PROD_DB_HOST') }}"
      user: "{{ env_var('PROD_DB_USER') }}"
      password: "{{ env_var('PROD_DB_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('PROD_DB_NAME') }}"
      schema: public # Or your production schema
      threads: 8