apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: "consolidate-data-{{ ts_nodash }}"
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "apache/spark:3.5.1-python3"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/work-dir/src/consolidate_data.py"  # 🔥 Different entrypoint
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never

  sparkConf:
    # Same MinIO S3a configs
    spark.kubernetes.driver.deleteOnTermination: "false"
    spark.kubernetes.executor.deleteOnTermination: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-logs/consolidate/"
    spark.hadoop.fs.s3a.endpoint: "http://minio.storage.svc.cluster.local:9000"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.sql.streaming.checkpointLocation: "s3a://spark-logs/checkpoints/consolidate"
    
    # Python path (imports main.py helpers)
    spark.driverEnv.PYTHONPATH: "/opt/spark/work-dir/src"
    spark.executorEnv.PYTHONPATH: "/opt/spark/work-dir/src"

  driver:
    cores: 1
    memory: "2g"  # More memory for data consolidation
    serviceAccount: "spark"
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
    # Mount the consolidate job sources directly from the ConfigMap so
    # the driver can find local:///opt/spark/work-dir/src/consolidate_data.py
    volumeMounts:
      - name: app-scripts
        mountPath: /opt/spark/work-dir/src
    volumes:
      - name: app-scripts
        configMap:
          name: consolidate-data-script

  executor:
    cores: 1
    instances: 2
    memory: "2g"
    # Executors also mount the same ConfigMap so imports work on executors.
    volumeMounts:
      - name: app-scripts
        mountPath: /opt/spark/work-dir/src
    volumes:
      - name: app-scripts
        configMap:
          name: consolidate-data-script

  packages:
    - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
    - org.apache.hadoop:hadoop-aws:3.3.6
    - com.amazonaws:aws-java-sdk-bundle:1.12.262

  sparkPodLabels:
    app: airflow-spark-consolidate
