apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: "consolidate-data-{{ ds_nanos }}"  # Simple templating (ds_nanos works)
  namespace: default  # ← Changed to default for Spark Operator to watch
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "apache/spark-py:3.5.1"                      # ✅ VALID public image
  imagePullPolicy: Always                            # ✅ Minikube can pull
  mainApplicationFile: "local:///app/src/consolidate_data.py"  # ✅ Your custom script
  sparkVersion: "3.5.1"                              # ✅ Match image version
  restartPolicy:
    type: Never

  sparkConf:                                          # ✅ Keep all your configs
    spark.kubernetes.driver.deleteOnTermination: "false"
    spark.kubernetes.executor.deleteOnTermination: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-logs/"          # ✅ MinIO logging
    spark.kubernetes.driver.label.app_kubernetes_io_name: "airflow-spark"

  driver:
    cores: 1
    memory: "1g"
    serviceAccount: "default"                        # ← Changed to default SA 
    env:                                              # ✅ MinIO credentials
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey

  executor:
    cores: 1
    instances: 2                                     # ✅ Production-ready
    memory: "2g"

  packages:                                           # ✅ Kafka + S3 (updated versions)
    - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
    - org.apache.hadoop:hadoop-aws:3.3.4

  sparkPodLabels:
    app: airflow-spark                               # ✅ Airflow pod watching
