apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: consolidate-data-job
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "psalmprax/spark-app:1.0.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/consolidate_data.py"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "1g"