apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: consolidate-data-job
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "psalmprax/spark-app:1.0.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/consolidate_data.py"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never

  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://minio.storage.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.sql.shuffle.partitions": "500"
    "spark.driver.extraClassPath": "/opt/spark/jars/*"
    "spark.executor.extraClassPath": "/opt/spark/jars/*"
    "spark.jars": >
      local:///opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.7.jar,
      local:///opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.7.jar,
      local:///opt/spark/jars/kafka-clients-3.5.1.jar,
      local:///opt/spark/jars/commons-pool2-2.11.1.jar,
      local:///opt/spark/jars/hadoop-aws-3.3.4.jar,
      local:///opt/spark/jars/aws-java-sdk-bundle-1.12.470.jar

  driver:
    cores: 1
    memory: "1g"
    serviceAccount: "spark"
    env:
      # MinIO S3A
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
      
      # 🔥 CORRECTED: Airflow PostgreSQL Service
      - name: DB_HOSTNAME
        value: "airflow-postgresql.airflow.svc.cluster.local"  # ✅ From your services
      - name: DB_PORT
        value: "5432"
      - name: DB_NAME
        value: "airflow"  # Airflow's default DB name
      - name: DB_USER
        value: "{{ conn.postgres_default.login }}"
      - name: DB_PASSWORD
        value: "{{ conn.postgres_default.password }}"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: my-kafka-cluster-my-nodepool-0.my-kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: paymentevents
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    env:
      # Copy ALL env vars (MinIO + PostgreSQL)
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
      - name: DB_HOSTNAME
        value: "airflow-postgresql.airflow.svc.cluster.local"
      - name: DB_PORT
        value: "5432"
      - name: DB_NAME
        value: "airflow"
      - name: DB_USER
        value: "{{ conn.postgres_default.login }}"
      - name: DB_PASSWORD
        value: "{{ conn.postgres_default.password }}"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: my-kafka-cluster-my-nodepool-0.my-kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: paymentevents