apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: "consolidate-data-{{ ts_nodash }}"
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "apache/spark:3.5.1-python3"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/work-dir/src/consolidate_data.py"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never

  sparkConf:                                          # ✅ Keep all your configs
    spark.kubernetes.driver.deleteOnTermination: "false"
    spark.kubernetes.executor.deleteOnTermination: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-logs/"          # ✅ MinIO logging
    spark.hadoop.fs.s3a.endpoint: "http://minio.storage.svc.cluster.local:9000"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.kubernetes.driver.label.app_kubernetes_io_name: "airflow-spark"
    # Your existing MinIO/S3a + CRITICAL volume fix:
    spark.kubernetes.driver.volumes.configMap.spark_job_script.defaultMode: "420"
    spark.kubernetes.executor.volumes.configMap.spark_job_script.defaultMode: "420"
    # Kafka streaming + fraud platform configs
    spark.sql.streaming.checkpointLocation: "s3a://spark-logs/checkpoints"

  driver:
    cores: 1
    memory: "1g"
    serviceAccount: "spark"
    volumeMounts:
      - name: "spark-job-script"
        mountPath: "/opt/spark/work-dir/src"
    env:                                              # ✅ MinIO credentials
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
  
  volumes:
    - name: "spark-job-script"
      configMap:
        name: "consolidate-data-script" # This ConfigMap will be created by the Airflow operator

  executor:
    cores: 1
    instances: 2                                     # ✅ Production-ready
    memory: "2g"
    labels:
      version: "3.5.1"

  packages:                                           # ✅ Kafka + S3 (updated versions)
    - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
    - org.apache.hadoop:hadoop-aws:3.3.6
    - com.amazonaws:aws-java-sdk-bundle:1.12.262

  sparkPodLabels:
    app: airflow-spark                               # ✅ Airflow pod watching
