apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: "on-prem-etl-{{ ts_nodash }}"
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "apache/spark:3.5.1-python3"
  mainApplicationFile: "local:///opt/spark/work-dir/src/main.py"
  sparkVersion: "3.5.1"
  
  sparkConf:
    spark.kubernetes.driver.deleteOnTermination: "false"
    spark.kubernetes.executor.deleteOnTermination: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-logs/"
    spark.hadoop.fs.s3a.endpoint: "http://minio.storage.svc.cluster.local:9000"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.sql.streaming.checkpointLocation: "s3a://spark-logs/checkpoints"
    spark.driverEnv.PYTHONPATH: "/opt/spark/work-dir/src"
    spark.executorEnv.PYTHONPATH: "/opt/spark/work-dir/src"
    
    # 🔥 POD TEMPLATES - Official Spark Operator method
    spark.kubernetes.driver.podTemplateFile: "local:///etc/spark-conf/driver-pod-template"
    spark.kubernetes.executor.podTemplateFile: "local:///etc/spark-conf/executor-pod-template"

  driver:
    cores: 1
    memory: "1g"
    serviceAccount: "spark"
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey

  executor:
    cores: 1
    instances: 2
    memory: "2g"
