apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-etl-job
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "psalmprax/spark-app:1.0.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/main.py"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never

  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
    volumeMounts:
      - name: spark-scripts
        mountPath: /opt/spark/work-dir
      - name: ivy-cache
        mountPath: /tmp/.ivy2
    volumes:
      - name: spark-scripts
        emptyDir: {}
      - name: ivy-cache
        emptyDir: {}

  executor:
    cores: 1
    instances: 2
    memory: "2g"
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
    volumeMounts:
      - name: spark-scripts
        mountPath: /opt/spark/work-dir
      - name: ivy-cache
        mountPath: /tmp/.ivy2
    volumes:
      - name: spark-scripts
        emptyDir: {}
      - name: ivy-cache
        emptyDir: {}

  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://minio.storage.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.jars.packages": "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1"
    # Point Ivy to a writable directory within the pod
    "spark.ivy.dir": "/tmp/.ivy2"
