apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: "on-prem-etl-{{ ds_nodash }}"
  namespace: default  # ← CHANGED! Operator watches this ✅
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "apache/spark-py:3.5.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/src/main.py"    
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never

  sparkConf:
    spark.kubernetes.driver.deleteOnTermination: "false"
    spark.kubernetes.executor.deleteOnTermination: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-logs/"
    spark.kubernetes.driver.label.app_kubernetes_io_name: "airflow-spark"

  driver:
    cores: 1
    memory: "1g"
    labels:
      version: "3.5.1"
    serviceAccount: "default"  # ← CHANGED! default SA in default ns ✅
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials  # ← Create in default ns
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey

  executor:
    cores: 1
    instances: 2
    memory: "2g"
    labels:
      version: "3.5.1"

  packages:
    - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
    - org.apache.hadoop:hadoop-aws:3.3.4

  sparkPodLabels:
    app: airflow-spark
