apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-streaming-payment-processor
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "psalmprax/spark-app:1.0.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/streaming_processor.py"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10

  # 🔥 FIXED: Kafka + MinIO env vars
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: "spark"
    env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "my-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: my-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: payment-events
  executor:
    cores: 1
    instances: 2
    memory: "2g"
    env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "my-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: my-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: payment-events
  # 🔥 FIXED: COMPLETE sparkConf
  sparkConf:
    # MinIO S3A (NO hardcoded credentials - use env vars)
    "spark.hadoop.fs.s3a.endpoint": "http://minio.storage.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    
    # 🔥 CRITICAL: ALL PACKAGES (Kafka + S3A)
    "spark.jars.packages": "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.kafka:kafka-clients:3.6.0,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262"
    
    "spark.sql.shuffle.partitions": "20"
    "spark.jars.ivy": "/tmp/.ivy2"
    "spark.ivy.dir": "/opt/spark/work-dir/.ivy2"
