apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-streaming-payment-processor
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "psalmprax/spark-app:1.0.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/streaming_processor.py"
  sparkVersion: "3.5.7" # Align with other jobs and Dockerfile
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10

  # 🔥 FIXED: Kafka + MinIO env vars
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: "spark"
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: my-kafka-cluster-my-nodepool-0.my-kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: paymentevents
  executor:
    cores: 1
    instances: 2
    memory: "2g"
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: my-kafka-cluster-my-nodepool-0.my-kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: paymentevents
  # 🔥 FIXED: COMPLETE sparkConf
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://minio.storage.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.sql.shuffle.partitions": "20"
    "spark.driver.extraClassPath": "/opt/spark/jars/*"
    "spark.executor.extraClassPath": "/opt/spark/jars/*"
    "spark.jars": >
      local:///opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.7.jar,
      local:///opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.7.jar,
      local:///opt/spark/jars/kafka-clients-3.5.1.jar,
      local:///opt/spark/jars/commons-pool2-2.11.1.jar,
      local:///opt/spark/jars/hadoop-aws-3.3.4.jar,
      local:///opt/spark/jars/aws-java-sdk-bundle-1.12.470.jar