apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-streaming-payment-processor
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "psalmprax/spark-app:1.0.0" # Assumes the same image with the new script added
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/streaming_processor.py"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: OnFailure # Streaming jobs can be restarted if they fail
    onFailureRetries: 3
    onFailureRetryInterval: 10

  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
    env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "my-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey

  executor:
    cores: 1
    instances: 2
    memory: "2g"
    env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "my-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: accesskey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secretkey

  # Spark-Submit parameters
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://minio.storage.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.access.key": "minio"
    "spark.hadoop.fs.s3a.secret.key": "minio123"
    "spark.sql.shuffle.partitions": "20" # Can be lower for streaming
    "spark.jars.ivy": "/tmp/.ivy2"
    # Add required packages for Kafka and S3A filesystem access (for MinIO)
    # Ensure versions are compatible with your Spark/Hadoop version.
    "spark.jars.packages": "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.kafka:kafka-clients:3.6.0,com.amazonaws:aws-java-sdk-bundle:1.12.262"
    "spark.ivy.dir": "/opt/spark/work-dir/.ivy2"
